export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
};

export const vendorConstants = {
  GET_VENDOR_REQUEST: "GET_VENDOR_REQUEST",
  GET_VENDOR_FAILURE: "GET_VENDOR_FAILURE",
  GET_VENDOR_SUCCESS: "GET_VENDOR_SUCCESS",
  ADD_VENDOR_REQUEST: "ADD_VENDOR_REQUEST",
  ADD_VENDOR_FAILURE: "ADD_VENDOR_FAILURE",
  ADD_VENDOR_SUCCESS: "ADD_VENDOR_SUCCESS",
  UPDATE_VENDOR_REQUEST: "UPDATE_VENDOR_REQUEST",
  UPDATE_VENDOR_FAILURE: "UPDATE_VENDOR_FAILURE",
  UPDATE_VENDOR_SUCCESS: "UPDATE_VENDOR_SUCCESS",
};

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_PRODUCT_BY_VENDOR_REQUEST: "GET_PRODUCT_BY_VENDOR_REQUEST",
  GET_PRODUCT_BY_VENDOR_FAILURE: "GET_PRODUCT_BY_VENDOR_FAILURE",
  GET_PRODUCT_BY_VENDOR_SUCCESS: "GET_PRODUCT_BY_VENDOR_SUCCESS",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
};

export const initDataConstants = {
  GET_INITIALDATA_REQUEST: "GET_INITIALDATA_REQUEST",
  GET_INITIALDATA_FAILURE: "GET_INITIALDATA_FAILURE",
  GET_INITIALDATA_SUCCESS: "GET_INITIALDATA_SUCCESS",
};

export const purchaseConstants = {
  GET_PURCHASE_ORDER_REQUEST: "GET_PURCHASE_ORDER_REQUEST",
  GET_PURCHASE_ORDER_SUCCESS: "GET_PURCHASE_ORDER_SUCCESS",
  GET_PURCHASE_ORDER_FAILURE: "GET_PURCHASE_ORDER_FAILURE",

  ADD_PURCHASE_ORDER_REQUEST: "ADD_PURCHASE_ORDER_REQUEST",
  ADD_PURCHASE_ORDER_SUCCESS: "ADD_PURCHASE_ORDER_SUCCESS",
  ADD_PURCHASE_ORDER_FAILURE: "ADD_PURCHASE_ORDER_FAILURE",
};

export const saleConstants = {
  GET_SALE_ORDER_REQUEST: "GET_SALE_ORDER_REQUEST",
  GET_SALE_ORDER_SUCCESS: "GET_SALE_ORDER_SUCCESS",
  GET_SALE_ORDER_FAILURE: "GET_SALE_ORDER_FAILURE",

  ADD_SALE_ORDER_REQUEST: "ADD_SALE_ORDER_REQUEST",
  ADD_SALE_ORDER_SUCCESS: "ADD_SALE_ORDER_SUCCESS",
  ADD_SALE_ORDER_FAILURE: "ADD_SALE_ORDER_FAILURE",
};

export const inventoryConstants = {
  GET_INVENTORY_REQUEST: "GET_INVENTORY_REQUEST",
  GET_INVENTORY_FAILURE: "GET_INVENTORY_FAILURE",
  GET_INVENTORY_SUCCESS: "GET_INVENTORY_SUCCESS",
};
